import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Header from './components/Header'
import Banner from './components/Banner'
import Productfeed from './components/Productfeed'



const inter = Inter({ subsets: ['latin'] })

export default function Home({products}) {
  return (
    <>
      <Head>
        <title>Ridamen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-100">
        <Header/>
          <Banner/>    
          <Productfeed products= {products}/>  
          
      </main>
    </>
  )
}

export async function getServerSideProps(context){
  const products = await fetch("https://fakestoreapi.com/products").then((res)=>res.json());
  return{props:{products,},};
}

